### ISSUE TITLE
Train Voxel2Mesh on own data

### ISSUE THREAD

**Issue by devskroy1** [cvlab-epfl/voxel2mesh#5]
Is it possible to train Voxel2Mesh on my own training data, which consists of 3D voxelized MRI scans?
Currently, I only see Dataloaders for the CHAOS and Hippocampus datasets.

Thanks

**Comment by udaranga3001** [comment]
Yes, you can. You need to write a data loader for your own data. You can copy the code from hippoccampus.py or chaos.py to a new file (inside data directory) and then update it to load your data. You mainly need to update `pre_process_dataset` function so that it loads your data.  You can rename the class names if you like. You don't need to change rest of the code.

**Comment by devskroy1** [comment]
Ok thanks!
