### ISSUE TITLE
how should i operate Synaptic junction dataset.

### ISSUE THREAD

**Issue by ineedtograd123** [cvlab-epfl/voxel2mesh#8]
hello i want to try your code but i had a question of operating dataset for Synaptic junction dataset. It looked like you made specific calls for chaos and hippocampus but not synaptic junction dataset. Should I make one for this dataset? thank you

**Comment by Puzzled-Hui** [comment]
Have the same question, wanna get response from you @udaranga3001 .Thanks!

**Comment by udaranga3001** [comment]
The file was not added since the Synaptic Junction dataset was only released later. Unfortunately, I don't maintain the codebase now. You are welcome to send me a pull request with the data loader. Please attach a link to the output tif file after training the model with the data loader so that I can verify the function.
